version: "3"
services:
  # NOTE: With protonvpn, the port forwarded isn't guaranteed to be stable 
  # The port has to be manually set instead.
  # To automate some of this, there's opt/cron-scripts/qbittorrent-portforward.sh,
  # which I personally run outside docker, because I'm not setting up an entire
  # account and image for something this trivial
  # Feel free to steal the script and shove it in a docker container, but this
  # is the path I've gone down.
  # Also note that the script requires ntfy cli, and posts to alerts with a priority
  # of 4 if anything fails. Remove those lines if you don't have ntfy
  # Also note that the gluetun location is hard-coded, just in case 
  # stuff changes
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - /etc/nova/gluetun:/gluetun
    restart: unless-stopped
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      # OpenVPN is unusable; the protocol is highly unstable, which keeps killing the port forwarding and killing the internal server
      # This is a long-standing bug that seems to be specific to OpenVPN
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<redacted>
      # Not sure if this is going to work reliably or not, but all the swiss servers support P2P, except one that's a Tor
      # server
      - SERVER_COUNTRIES=Switzerland
      - VPN_PORT_FORWARDING=on
      - TZ=Europe/Oslo
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      # required to not break the port forwarding script.
      # Yes, I could add a password, but the server is never exposed and I don't care
      - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE='{"auth":"none"}'
  qbittorrent:
    # v2 is unusable
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    volumes:
      - /media/NAS/torrent/config:/config
      - /media/NAS/torrent/downloads:/downloads
    restart: unless-stopped

